# Generated by Django 5.1.2 on 2024-10-29 14:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='宠物名称')),
                ('breed', models.CharField(blank=True, max_length=50, verbose_name='品种')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(100)], verbose_name='体重(kg)')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('gender', models.CharField(choices=[('M', '公'), ('F', '母')], max_length=1, verbose_name='性别')),
                ('is_sterilized', models.BooleanField(default=False, verbose_name='是否绝育')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pets/', verbose_name='照片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL, verbose_name='主人')),
            ],
            options={
                'verbose_name': '宠物',
                'verbose_name_plural': '宠物',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PetHealthRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='记录日期')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('description', models.TextField(verbose_name='详细描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='pets.pet', verbose_name='宠物')),
            ],
            options={
                'verbose_name': '健康记录',
                'verbose_name_plural': '健康记录',
                'ordering': ['-date'],
            },
        ),
    ]
