# Generated by Django 5.1.2 on 2024-11-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='weight',
        ),
        migrations.AddField(
            model_name='pet',
            name='size',
            field=models.CharField(choices=[('S', '小型犬 (8kg以下)'), ('M', '中型犬 (8-15kg)'), ('L', '大型犬 (16-25kg)')], default='M', help_text='请选择宠物体型', max_length=1, verbose_name='体型'),
            preserve_default=False,
        ),
    ]
